const express = require('express');
const fetch = require('node-fetch');
const app = express();

app.use(express.json());

const DISCORD_WEBHOOK = 'https://discord.com/api/webhooks/1420364294448615507/-Px9-IXMsJWh1p6CixZnUUnxad5FjpM0mahJRiPByiCKqQiLtH4ARNss_o1NCwIApqlr/github';
const BRANCH_TO_NOTIFY = 'dev'; // Only notify for this branch

app.post('/github-webhook', async (req, res) => {
  const payload = req.body;
  const branch = payload.ref.replace('refs/heads/', '');

  if (branch !== BRANCH_TO_NOTIFY) return res.sendStatus(200); // ignore other branches

  const commitMessages = payload.commits
    .map(c => `**${c.author.name}**: ${c.message}`)
    .join('\n');

  await fetch(DISCORD_WEBHOOK, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ content: `Branch \`${branch}\` updated:\n${commitMessages}` })
  });

  res.sendStatus(200);
});

app.listen(3000, () => console.log('Webhook server running on port 3000'));
