name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send commit info to Discord
        run: |
          AUTHOR="${{ github.event.head_commit.author.name }}"
          BRANCH="${{ github.ref_name }}"
          COMMIT_URL="${{ github.event.head_commit.url }}"
          
          CHANGED_FILES=$(jq -r '.commits[].added[], .commits[].modified[], .commits[].removed[]' $GITHUB_EVENT_PATH | grep '^resources/' | cut -d/ -f2 | sort | uniq)
          
          if [ -z "$CHANGED_FILES" ]; then
            CHANGED_FILES="None"
          fi

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                     \"content\": \"🚀 **Update pushed by $AUTHOR**\n**Branch:** $BRANCH\n**Changed Resources:** $CHANGED_FILES\n🔗 Commit: $COMMIT_URL\"
                   }" \
               https://discord.com/api/webhooks/1420364294448615507/-Px9-IXMsJWh1p6CixZnUUnxad5FjpM0mahJRiPByiCKqQiLtH4ARNss_o1NCwIApqlr
